### ISSUE TITLE
R markdown CV template doesn't Knit

### ISSUE THREAD

**Issue by ShiyuanChen13** [StatSocAus/venables-award#1]
For some reason, I cannot Knit the R markdown CV template. Here are the error messages I saw. (I am new to R so I could have missed many possible ways to fix these issues)

Error: LaTeX failed to compile CV_test1.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips.
In addition: Warning message:
In system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) :
  '"pdflatex"' not found

I tried to install LaTex, but the error message says it is not available for my R version although I have updated to the latest version. I have tinytex installed too.

Thank you very much!

**Comment by deanmarchiori** [comment]
Hi, it looks like you are raising an issue related to rendering CV templates from the {vitae} package? 

The best place to raise this issue would be on the {vitae} package github. https://github.com/mitchelloharawild/vitae

Although it sounds like your issue is more related to your local setup rather than a bug in the package, so perhaps stackoverflow might be useful? Here is a very similar question yours. I hope it helps. 

https://stackoverflow.com/questions/63270667/how-to-compile-a-pdf-in-rstudio-markdown

Good Luck.
